In [3]:
import numpy as np

In [4]:
x = np.random.randint(0,10,(2,2))
x

array([[8, 5],
       [9, 0]], dtype=int32)

In [5]:
y = np.random.randint(0,10,(2,2))
y

array([[5, 8],
       [2, 6]], dtype=int32)

In [6]:
z = np.add(x,y)
z

array([[13, 13],
       [11,  6]], dtype=int32)

In [4]:
x = ['data','sci',1,2,3]
y = np.array(x)
print(y)

['data' 'sci' '1' '2' '3']


In [4]:
arr = np.array([[1,2,3],[4,5,6]])

In [5]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
print(arr.shape)

(2, 3)


In [7]:
print(arr.size)

6


In [11]:
print(arr.reshape([3,2]))

[[1 2]
 [3 4]
 [5 6]]


In [12]:
3

3

In [15]:
zeros_arr = np.zeros((3,4))
print(zeros_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
ones_arr = np.ones((3,4))
print(ones_arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
a = np.array([1,2,3])
b = np.array([[1],[2],[3]])
print(b)
print(a+b)


[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [30]:
arr = np.array([1, 2, 3, 33,4, 5,6,10,21])
print("mean:", np.mean(arr))

mean: 9.444444444444445


In [32]:
print("mean:", np.median(arr))

mean: 5.0


In [33]:
print("std:", np.std(arr))

std: 10.100727268767566


In [12]:
from numpy import random
sales = random.randint(100, size=(10, 5))

In [13]:
print(sales)

[[70 25 65 17 41]
 [16 96 18 13 25]
 [86 23  9 50 96]
 [69  7 73 60  3]
 [58 36 99 48 18]
 [29  0 53 69 77]
 [ 1 98 45  9 98]
 [86 41 44 51 12]
 [60 36  0 89  1]
 [23 37 21 33 40]]


In [14]:
print(sales[1:4,2:4])

[[18 13]
 [ 9 50]
 [73 60]]


In [17]:
print(sales[-4:-1,-4:-1])

[[98 45  9]
 [41 44 51]
 [36  0 89]]


In [24]:
x

array([[2, 7],
       [7, 5]], dtype=int32)

In [27]:
y

array([[2, 8],
       [4, 2]], dtype=int32)

In [20]:
print(np.add(x,y))

[[ 3 15]
 [15  5]]


In [21]:
print(np.subtract(x,y))

[[ 1 -1]
 [-1  5]]


In [29]:
print(np.divide(x,y))

[[1.    0.875]
 [1.75  2.5  ]]


In [30]:
print(np.floor_divide(x,y))

[[1 0]
 [1 2]]


In [31]:
print(np.round(np.divide(x,y)))

[[1. 1.]
 [2. 2.]]


In [32]:
print(np.ceil(np.divide(x,y)))

[[1. 1.]
 [2. 3.]]


In [34]:
print(np.fix(x,y))

[[2 7]
 [7 5]]


In [37]:
x= np.random.randint(0,2,(4,4))

In [38]:
x

array([[1, 0, 1, 1],
       [1, 0, 1, 0],
       [1, 1, 1, 1],
       [0, 1, 1, 1]], dtype=int32)

In [39]:
x.max(axis=0)

array([1, 1, 1, 1], dtype=int32)

In [41]:
x.min(axis=1)

array([0, 0, 1, 0], dtype=int32)

In [42]:
x= np.random.randint(0,10,(4,4))

In [43]:
x

array([[0, 1, 4, 8],
       [6, 6, 3, 3],
       [9, 4, 1, 1],
       [3, 8, 7, 5]], dtype=int32)

In [44]:
x.max(axis=1)

array([8, 6, 9, 8], dtype=int32)

In [46]:
x.min(axis=0)

array([0, 1, 1, 1], dtype=int32)

In [48]:
x.argmax(axis=1)

array([3, 0, 0, 1])

In [49]:
x.argm(axis=0)

array([2, 3, 3, 0])

In [50]:
data = np.random.randint(0,100,10)

In [51]:
data

array([89, 20, 97, 19, 90, 25, 17, 67, 66,  1], dtype=int32)

In [52]:
data>50

array([ True, False,  True, False,  True, False, False,  True,  True,
       False])

In [54]:
data[data>50]

array([89, 97, 90, 67, 66], dtype=int32)

In [55]:
np.where(data>50, 'high','low')

array(['high', 'low', 'high', 'low', 'high', 'low', 'low', 'high', 'high',
       'low'], dtype='<U4')

In [56]:
data = np.random.randint(0,10,10)

In [57]:
data

array([9, 4, 1, 9, 9, 3, 9, 9, 8, 8], dtype=int32)

In [58]:
data.shape

(10,)

In [59]:
data.reshape(5,2)

array([[9, 4],
       [1, 9],
       [9, 3],
       [9, 9],
       [8, 8]], dtype=int32)

In [62]:
data.ravel()

array([9, 4, 1, 9, 9, 3, 9, 9, 8, 8], dtype=int32)

In [63]:
data.flatten()

array([9, 4, 1, 9, 9, 3, 9, 9, 8, 8], dtype=int32)

In [64]:
sales = np.random.randint(10,100,10)

In [67]:
sales[sales>50]

array([86, 83, 55, 96, 88], dtype=int32)

In [68]:
len(sales[sales>50])

5

In [95]:
sales = np.random.randint(1,100,(10,5))

In [96]:
sales

array([[72, 25, 53, 67,  5],
       [50, 36, 55, 60, 51],
       [67, 39, 77, 55,  6],
       [52, 80, 96, 98, 19],
       [47, 36, 13, 94, 15],
       [85, 65,  1, 16, 77],
       [55, 31, 52,  6, 17],
       [96,  6, 97, 52, 66],
       [31, 19, 66, 96, 25],
       [35, 13, 48, 42, 40]], dtype=int32)

In [120]:
sales[:,0]

array([72, 50, 67, 52, 47, 85, 55, 96, 31, 35], dtype=int32)

In [97]:
sales[0,].sum()

np.int64(222)

In [98]:
sales.sum(axis=1)

array([222, 252, 244, 345, 205, 244, 161, 317, 237, 178])

In [99]:
sales.argmax(axis=1)

array([0, 3, 2, 3, 3, 0, 0, 2, 3, 2])

In [100]:
sales[:,0]

array([72, 50, 67, 52, 47, 85, 55, 96, 31, 35], dtype=int32)

In [105]:
sales[:,0].argmax()+1

np.int64(8)

In [124]:
sales.mean(axis=0)

array([59. , 35. , 55.8, 58.6, 32.1])

In [125]:
sales.mean(axis=0).argmax()+1

np.int64(1)

In [191]:
sales = np.random.randint(1,100,(10,5))

In [192]:
sales

array([[21, 85, 34,  2, 20],
       [83,  3, 37, 31, 55],
       [11, 96, 54, 11, 98],
       [46, 12, 92, 94, 19],
       [24, 67, 65, 66, 89],
       [56,  8, 98, 52, 56],
       [52, 50, 94, 29, 74],
       [52, 23, 76, 89, 23],
       [39,  4, 11, 97, 63],
       [47,  5, 13, 62, 83]], dtype=int32)

In [193]:
sales[:,2]

array([34, 37, 54, 92, 65, 98, 94, 76, 11, 13], dtype=int32)

In [142]:
(sales[:,0]/sales[:,2])

array([ 0.27272727,  0.4       ,  4.33333333,  0.58333333,  3.17241379,
       10.55555556,  2.23076923,  0.91549296,  0.56818182,  1.33333333])

In [141]:
(sales[:,0]/sales[:,2]).astype(int)

array([ 0,  0,  4,  0,  3, 10,  2,  0,  0,  1])

In [140]:
(sales[:,0]/sales[:,2]).argmax()+1

np.int64(6)

In [143]:
sales

array([[ 3, 54, 11, 80, 51],
       [14, 60, 35, 26, 40],
       [91, 77, 21, 87, 89],
       [42, 88, 72, 35, 34],
       [92, 83, 29, 84, 54],
       [95, 28,  9, 26, 27],
       [87, 78, 39, 72, 31],
       [65, 23, 71, 91, 74],
       [25, 20, 44, 34, 37],
       [24, 19, 18, 30, 98]], dtype=int32)

In [194]:
y = np.random.randint(0,2,(10,1))

In [195]:
y

array([[1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0]], dtype=int32)

In [196]:
sales = np.append(sales, y, axis=1)

In [197]:
sales

array([[21, 85, 34,  2, 20,  1],
       [83,  3, 37, 31, 55,  1],
       [11, 96, 54, 11, 98,  0],
       [46, 12, 92, 94, 19,  1],
       [24, 67, 65, 66, 89,  1],
       [56,  8, 98, 52, 56,  1],
       [52, 50, 94, 29, 74,  0],
       [52, 23, 76, 89, 23,  1],
       [39,  4, 11, 97, 63,  0],
       [47,  5, 13, 62, 83,  0]], dtype=int32)

In [206]:
sales[sales[:,-1]]

array([[83,  3, 37, 31, 55,  1],
       [83,  3, 37, 31, 55,  1],
       [21, 85, 34,  2, 20,  1],
       [83,  3, 37, 31, 55,  1],
       [83,  3, 37, 31, 55,  1],
       [83,  3, 37, 31, 55,  1],
       [21, 85, 34,  2, 20,  1],
       [83,  3, 37, 31, 55,  1],
       [21, 85, 34,  2, 20,  1],
       [21, 85, 34,  2, 20,  1]], dtype=int32)

In [207]:
sales[sales[:,-1]]

array([[83,  3, 37, 31, 55,  1],
       [83,  3, 37, 31, 55,  1],
       [21, 85, 34,  2, 20,  1],
       [83,  3, 37, 31, 55,  1],
       [83,  3, 37, 31, 55,  1],
       [83,  3, 37, 31, 55,  1],
       [21, 85, 34,  2, 20,  1],
       [83,  3, 37, 31, 55,  1],
       [21, 85, 34,  2, 20,  1],
       [21, 85, 34,  2, 20,  1]], dtype=int32)

In [201]:
sales[sales[:,-1]==1].sum()

np.int64(1484)

In [202]:
sales[sales[:,-1]==0].sum()

np.int64(993)

In [204]:
if sales[sales[:,-1]==1].sum() > sales[sales[:,-1]==0].sum():
    print('sales with drive through')
else:
    print('with out drive through')

sales with drive through


In [208]:
empty = np.empty((3,4))
empty

array([[2.03711596e-312, 2.33419537e-313, 4.84184333e-322,
        1.06099790e-312],
       [6.15378780e-313, 3.65608578e-322, 8.48798318e-314,
        2.05833592e-312],
       [3.11261357e-322, 1.06099790e-313, 1.31563739e-312,
        4.10074486e-322]])

In [210]:
full_array = np.full((3, 3), 6)
full_array

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [213]:
print(np.zeros((3,3)))
print(np.ones((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [214]:
tolist = np.random.randint(1,10,(3,3))
tolist

array([[4, 8, 7],
       [3, 7, 3],
       [4, 7, 9]], dtype=int32)

In [215]:
tolist.tolist()

[[4, 8, 7], [3, 7, 3], [4, 7, 9]]

In [234]:
n_arr = np.array([[10.5, 22.5, 3.8],[41, np.nan, np.nan]])
#n_arr = np.array([[10.5, 22.5, 3.8],[41, np.nan, np.nan]])
n_arr

array([[10.5, 22.5,  3.8],
       [41. ,  nan,  nan]])

In [235]:
cleaned_arr = n_arr[~np.isnan(n_arr).any(axis=1)]
#n_arr

print(n_arr[~np.isnan(n_arr).any(axis=1),:])

[[10.5 22.5  3.8]]


In [231]:
print(n_arr[:, ~np.isnan(n_arr).any(axis=0)]) 

[[10.5]
 [41. ]]


In [236]:
shape_arr = np.random.randint(0,10,(3,4))
shape_arr

array([[5, 7, 7, 1],
       [7, 5, 5, 5],
       [3, 7, 8, 2]], dtype=int32)

In [237]:
print(shape_arr.shape)

(3, 4)


In [241]:
print(np.squeeze(shape_arr).shape)

(3, 4)


In [7]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [26]:
x = np.arange(9).reshape(1,3,3)
y = np.arange(9).reshape(3,3)

In [30]:
x
#y

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [36]:
in_arr = np.arange(12).reshape(2, 3, 2) 
+

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [41]:
arr = np.array([[9, 4, 9, 4],  
                   [9, 4, 9, 4], 
                   [4, 4, 9, 7], 
                   [4, 9, 4, 3]]) 
arr

array([[9, 4, 9, 4],
       [9, 4, 9, 4],
       [4, 5, 9, 7],
       [2, 9, 4, 3]])

In [43]:
repr(arr).count("9, 4") 

'array([[9, 4, 9, 4],\n       [9, 4, 9, 4],\n       [4, 5, 9, 7],\n       [2, 9, 4, 3]])'

In [66]:
arr.flatten()
np.bincount(arr).argmax()

ValueError: object too deep for desired array

In [51]:
ele = 4
count = 0
for i in arr.flatten():
    if i == 4:
        count += 1
print("ele:"+ str(count))

ele:6


In [52]:
c = np.count_nonzero(arr == 4)

In [53]:
c

6

In [56]:
count = (arr == 4)

In [63]:
count = arr.tolist().count(4)

In [64]:
count

0

In [76]:
array = np.ones((2, 2)) 
array

array([[1., 1.],
       [1., 1.]])

In [77]:
#array = np.pad(array, pad_width=1, mode='constant', constant_value=0)
array = np.pad(array, pad_width=1, mode='constant', constant_values=2)
array

array([[2., 2., 2., 2.],
       [2., 1., 1., 2.],
       [2., 1., 1., 2.],
       [2., 2., 2., 2.]])

In [78]:
arr = np.random.randint(1,10,(2,2))
arr

array([[9, 8],
       [9, 7]], dtype=int32)

In [79]:
y = np.flip(arr)

In [80]:
y

array([[7, 9],
       [8, 9]], dtype=int32)

In [84]:
arr = np.random.randint(1,10,(3,4))
arr

array([[4, 9, 5, 6],
       [7, 1, 2, 9],
       [2, 5, 2, 2]], dtype=int32)

In [85]:
arr.reshape(4,3)

array([[4, 9, 5],
       [6, 7, 1],
       [2, 9, 2],
       [5, 2, 2]], dtype=int32)

In [87]:
np.shape(arr)

(3, 4)

In [98]:
arr = np.random.randint(1,10,(3,4))
arr

array([[9, 4, 3, 8],
       [6, 9, 6, 7],
       [4, 5, 5, 2]], dtype=int32)

In [99]:
y=arr.ravel()
y

array([9, 4, 3, 8, 6, 9, 6, 7, 4, 5, 5, 2], dtype=int32)

In [102]:
x= arr.flatten()
x

array([9, 4, 3, 8, 6, 9, 6, 7, 4, 5, 5, 2], dtype=int32)

In [105]:
x[0] = 200
x

array([200,   4,   3,   8,   6,   9,   6,   7,   4,   5,   5,   2],
      dtype=int32)

In [107]:
arr

array([[9, 4, 3, 8],
       [6, 9, 6, 7],
       [4, 5, 5, 2]], dtype=int32)

In [104]:
y

array([9, 4, 3, 8, 6, 9, 6, 7, 4, 5, 5, 2], dtype=int32)

In [108]:
a = np.array([(1,2,3,4),(3,1,4,2)])
a

array([[1, 2, 3, 4],
       [3, 1, 4, 2]])

In [109]:
ra = np.ravel(a)
ra

array([1, 2, 3, 4, 3, 1, 4, 2])

In [110]:
ra[3] = 44

In [111]:
ra

array([ 1,  2,  3, 44,  3,  1,  4,  2])

In [112]:
a

array([[ 1,  2,  3, 44],
       [ 3,  1,  4,  2]])

In [113]:
a = np.array([(1,2,3,4),(3,1,4,2)])
a

array([[1, 2, 3, 4],
       [3, 1, 4, 2]])

In [114]:
c = a.flatten()
c

array([1, 2, 3, 4, 3, 1, 4, 2])

In [115]:
c[3] = 40
c

array([ 1,  2,  3, 40,  3,  1,  4,  2])

In [116]:
a

array([[1, 2, 3, 4],
       [3, 1, 4, 2]])